using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Web;
using System.Web.SessionState;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.HtmlControls;

namespace NASSCOM_NAC.NACdb
{
	/// <summary>
	/// Summary description for CompanyHomePage.
	/// </summary>
	public partial class CompanyHomePage : System.Web.UI.Page
	{
		protected System.Web.UI.WebControls.LinkButton lbHireExit;
	
		#region PageLoad 

		protected void Page_Load(object sender, System.EventArgs e)
		{
			lnkLogOut.Attributes.Add("onclick","CloseWindow();");

			if(Session["CompanyId"] == null || Session["CompanyName"] == null)
			{
				Response.Redirect("./LoginPage.aspx",false);
			}
			else
			{
				lblCompanyName.Text=Session["CompanyName"].ToString();
			}
			
			if(!IsPostBack)
			{
				if(Session["IsUpdated"] != null)
				{
					if(Session["IsUpdated"].ToString() == "False")
					{
						this.Page.RegisterClientScriptBlock("Message", "<script language=javascript>alert('Please change your autogenerated password, for security reasons');</script>");
					}
				}
			}
		}


		#endregion

		#region Web Form Designer generated code
		override protected void OnInit(EventArgs e)
		{
			//
			// CODEGEN: This call is required by the ASP.NET Web Form Designer.
			//
			InitializeComponent();
			base.OnInit(e);
		}
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{    

		}
		#endregion

		#region LogOut 

		protected void lnkLogOut_Click(object sender, System.EventArgs e)
		{
			Session.Abandon();
			Response.Write("<script language=javascript>self.close();</script>");
			string nextpage = "LoginPage.aspx";
			Response.Write("<script language=javascript>");
			Response.Write("{");
			Response.Write(" var Backlen=history.length;");
			Response.Write(" history.go(-Backlen);");
			Response.Write(" window.location.href='" + nextpage + "'; ");
			Response.Write("}");
			Response.Write("</script>");  

			Response.Cache.SetExpires(DateTime.Parse(DateTime.  Now.ToString()));
			Response.Cache.SetCacheability(HttpCacheability.Private);
			Response.Cache.SetNoStore();
			Response.AppendHeader("Pragma", "no-cache");
			
		}


		#endregion

		#region CandidateSearch

		protected void lnkCandidateSearch_Click(object sender, System.EventArgs e)
		{
			Response.Redirect("CandidateSearchPage.aspx",false);
		}


		#endregion

		#region CompanyProfile

		protected void lnkCompanyProfile_Click(object sender, System.EventArgs e)
		{
			Response.Redirect("CompanyProfile.aspx",false);
		}


		#endregion

		#region ChangePassword

		protected void lnkChangePassword_Click(object sender, System.EventArgs e)
		{
			Response.Redirect("ChangePassword.aspx",false);
		}

		#endregion

		#region Hire_Exit_Click

		protected void lnkHireExit_Click(object sender, System.EventArgs e)
		{
			Response.Redirect("CompanyHire.aspx",false);
		}


		#endregion

		#region View_Hired_Candidates

		protected void lnkViewHiredCandidates_Click(object sender, System.EventArgs e)
		{
			Response.Redirect("HiredCandidates.aspx",false);
		}

		#endregion

	}
}
